# Generated by Django 2.1.5 on 2019-02-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_tag_posts'),
        ('posts', '0007_auto_20181217_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(through='tags.TagMap', to='tags.Tag'),
        ),
    ]
