# Generated by Django 2.1.5 on 2019-02-04 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20181217_1739'),
        ('tags', '0003_auto_20190204_1652'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagmap',
            unique_together={('tag_id', 'post_id')},
        ),
    ]
