# Generated by Django 2.1.5 on 2019-02-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20181217_1739'),
        ('tags', '0005_auto_20190204_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(through='tags.TagMap', to='posts.Post'),
        ),
    ]
